/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.mobile.vo;

import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-04-30 08:52:44
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class AttachmentVO extends SuperVO {
	private java.lang.String pk_attachment;
	private java.lang.String pk_message;
	private java.lang.String pk_file;
	private java.lang.String filename;
	private java.lang.Integer filesize;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_ATTACHMENT = "pk_attachment";
	public static final String PK_MESSAGE = "pk_message";
	public static final String PK_FILE = "pk_file";
	public static final String FILENAME="filename";
	public static final String FILESIZE="filesize";

	/**
	 * 属性pk_attachment的Getter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @return java.lang.String
	 */
	public java.lang.String getPk_attachment() {
		return pk_attachment;
	}

	/**
	 * 属性pk_attachment的Setter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @param newPk_attachment java.lang.String
	 */
	public void setPk_attachment(java.lang.String newPk_attachment) {
		this.pk_attachment = newPk_attachment;
	}

	/**
	 * 属性pk_message的Getter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @return java.lang.String
	 */
	public java.lang.String getPk_message() {
		return pk_message;
	}

	/**
	 * 属性pk_message的Setter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @param newPk_message java.lang.String
	 */
	public void setPk_message(java.lang.String newPk_message) {
		this.pk_message = newPk_message;
	}

	/**
	 * 属性pk_file的Getter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @return java.lang.String
	 */
	public java.lang.String getPk_file() {
		return pk_file;
	}

	/**
	 * 属性pk_file的Setter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @param newPk_file java.lang.String
	 */
	public void setPk_file(java.lang.String newPk_file) {
		this.pk_file = newPk_file;
	}

	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @param newDr java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-04-30 08:52:44
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * <p>取得父VO主键字段.
	 * <p>
	 * 创建日期:2010-04-30 08:52:44
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>取得表主键.
	 * <p>
	 * 创建日期:2010-04-30 08:52:44
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_attachment";
	}

	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-04-30 08:52:44
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "sm_msg_attachment";
	}

	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-04-30 08:52:44
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "sm_msg_attachment";
	}

	/**
	 * 按照默认方式创建构造子.
	 *
	 * 创建日期:2010-04-30 08:52:44
	 */
	public AttachmentVO() {
		super();
	}

	public java.lang.String getFilename() {
		return filename;
	}

	public void setFilename(java.lang.String filename) {
		this.filename = filename;
	}

	public java.lang.Integer getFilesize() {
		return filesize;
	}

	public void setFilesize(java.lang.Integer filesize) {
		this.filesize = filesize;
	}

//	public IVOMeta getMetaData() {
//		IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("uap.attachment");
//		return meta;
//	}
}
